### ISSUE TITLE
got an unexpected keyword argument 'timestep_limit'

### ISSUE THREAD

**Issue by l45k** [MattChanTK/gym-maze#8]
I have the following issue:

Traceback (most recent call last):
  File "/mnt/c/Users/lkunzcik/PycharmProjects/gym-maze/test.py", line 7, in <module>
    import gym_maze
  File "/mnt/c/Users/lkunzcik/PycharmProjects/gym-maze/gym_maze/__init__.py", line 7, in <module>
    timestep_limit=2000,
  File "/home/l33k/py/lib/python3.6/site-packages/gym/envs/registration.py", line 153, in register
    return registry.register(id, **kwargs)
  File "/home/l33k/py/lib/python3.6/site-packages/gym/envs/registration.py", line 147, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'

The problem is that the keyword timestep_limit was renamed to max_episode_steps.

**Comment by MattChanTK** [comment]
Thanks for fixing the issue!

**Comment by Yifeng-Peng** [comment]
Thanks!

**Comment by haoruili699** [comment]
Thanks!
